package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.buildFeatures.FileContentReplacer
import jetbrains.buildServer.configs.kotlin.buildFeatures.replaceContent
import jetbrains.buildServer.configs.kotlin.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the buildType with id = 'Build'
accordingly, and delete the patch script.
*/
changeBuildType(RelativeId("Build")) {
    features {
        add {
            replaceContent {
                fileRules = "**/appsettings.json"
                pattern = "%secret-value-for-tc%"
                regexMode = FileContentReplacer.RegexMode.FIXED_STRINGS
                replacement = "team city"
                customEncodingName = ""
            }
        }
    }
}
